export const HIRING_PANEL_PROGRESS_LABELS = [
  'Elite Manager 1 reviewing your resume…',
  'Elite Manager 2 reviewing your resume…',
  'Elite Manager 3 reviewing your resume…',
  'Elite Manager 4 reviewing your resume…',
  'Elite Manager 5 reviewing your resume…',
  'Elite Manager 6 reviewing your resume…',
  'Elite Manager 7 reviewing your resume…',
  'Elite Manager 8 reviewing your resume…',
  'Elite Manager 9 reviewing your resume…',
  'Elite Manager 10 reviewing your resume…',
  'Synthesizing panel feedback…',
  'Rewriting outcome-driven bullets…',
  'Validating revisions against critiques…',
  'Iterating draft for maximum impact…',
  'Finalizing polished output…',
] as const
